name: Generate Bluhash
  # You may pin to the exact commit or the version.
  # uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
    
on:
  workflow_dispatch:
     
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: dart-lang/setup-dart@v1
       with:
         sdk: 3.1.0
     - name: Build blurhash
       working-directory: .github/workflows/blurhash/jackboxutility_blurhash
       run: dart pub get && dart run jackboxutility_blurhash.dart https://raw.githubusercontent.com/AkiraArtuhaxis/JackboxUtility-Server-en/main/api/v2/packs.json https://raw.githubusercontent.com/AkiraArtuhaxis/JackboxUtility-Server-en/main/assets
     - uses: actions/upload-artifact@v3
       with:
          name: blurHashes.json
          path: .github/workflows/blurhash/jackboxutility_blurhash/out/blurHashes.json
